USE [ML635232534]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 07-05-2020 16:29:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST NAME] [varchar](max) NOT NULL,
	[LAST NAME] [varchar](max) NOT NULL,
	[ADDRESS] [varchar](max) NOT NULL,
	[CITY] [varchar](max) NOT NULL,
	[PROVINCE] [varchar](max) NOT NULL,
	[POSTAL CODE] [varchar](50) NOT NULL,
	[PHONE NUMBER] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

