USE [ML635232534]
GO

/****** Object:  Table [dbo].[Payments]    Script Date: 07-05-2020 16:38:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Payments](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CHANGE DATE] [datetime] NOT NULL,
	[CHANGED FIELD] [bit] NOT NULL,
	[OLD VALUE] [varchar](max) NOT NULL,
	[NEW VALUE] [varchar](max) NOT NULL,
	[LEASEID] [int] NOT NULL,
 CONSTRAINT [PK_payments] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

