USE [ML635232534]
GO

/****** Object:  Table [dbo].[Vehicles]    Script Date: 11-05-2020 18:07:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Vehicles](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VIN] [varchar](450) NOT NULL,
	[MODEL] [int] NOT NULL,
	[TYPE] [int] NOT NULL,
	[COLOUR] [int] NOT NULL,
	[YEAR] [datetime2](7) NOT NULL,
	[KILOMETERS] [float] NOT NULL,
	[NEW OR EW-LEASE] [bit] NOT NULL,
	[BOOK VALUE] [money] NOT NULL,
	[AUTOMATIC TRANSMISSION] [bit] NOT NULL,
	[AIR CONDITIONING] [bit] NOT NULL,
	[POWER LOCKS] [bit] NOT NULL,
 CONSTRAINT [PK_Vehicles] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
