USE [ML635232534]
GO

/****** Object:  Table [dbo].[Leases]    Script Date: 07-05-2020 16:32:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Leases](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[START DATE] [datetime2](7) NOT NULL,
	[FIRST PAYMENT DATE] [datetime2](7) NOT NULL,
	[MONTHLY PAYMENT] [money] NOT NULL,
	[MONTHLY PAYMENT COUNT] [int] NOT NULL,
	[VEHICLEID] [int] NOT NULL,
	[CUSTOMERID] [int] NOT NULL,
	[TERMS] [ntext] NOT NULL,
 CONSTRAINT [PK_LEASES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

